### ISSUE TITLE
调用BundleBean方法得到了”No qualifying bean of type '<Facade Class名>' available“的报错

### ISSUE THREAD

**Issue by galaxyyao** [qianxingchuan/doraemon#1]
你好，
我尝试用SpringBoot作为启动程序做了个范例。在打印bundle path/打印ClassLoader的步骤都很顺利，但在调用实现了Facade接口的BundleBean方法的时候报错了如下的错误：
```
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.demo.doraemon.facade.DemoFacade' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:352)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1127)
	at com.galaxy.demo.doraemon.bundle1.run.BundleRun.getBundleBean(BundleRun.java:30)
```
我的SpringBoot程序的代码如下，基本和范例中的main程序代码一致。
```java
@SpringBootApplication
public class DoraemonDemoAppApplication {

	public static void main(String[] args) {
		SpringApplication.run(DoraemonDemoAppApplication.class, args);

		List<RunDoraemonBundle> runDoraemonBundles = new ArrayList<>();

		String bundle1Path = DoraemonDemoAppApplication.class.getResource("/doraemon-bundle1-1.0.0-SNAPSHOT-release.zip").getPath();
		String bundle2Path = DoraemonDemoAppApplication.class.getResource("/doraemon-bundle2-1.0.0-SNAPSHOT-release.zip").getPath();
		System.out.println("bundle1 path is " + bundle1Path);
		System.out.println("bundle2 path is " + bundle2Path);
		RunDoraemonBundle runDoraemonBundle1 = new RunDoraemonBundle(bundle1Path, null);
		runDoraemonBundle1.run();
		runDoraemonBundles.add(runDoraemonBundle1);

		RunDoraemonBundle runDoraemonBundle2 = new RunDoraemonBundle(bundle2Path, null);
		runDoraemonBundle2.run();
		runDoraemonBundles.add(runDoraemonBundle2);

		AsgardClassLoader bundle1ClassLoader = runDoraemonBundle1.getBundle().getBundleClassLoader();
		AsgardClassLoader bundle2ClassLoader = runDoraemonBundle2.getBundle().getBundleClassLoader();
		ClassLoader defaultClassLoader = Thread.currentThread().getContextClassLoader();
		System.out.println(defaultClassLoader);
		System.out.println(bundle1ClassLoader);
		System.out.println(bundle2ClassLoader);

		Thread.currentThread().setContextClassLoader(bundle1ClassLoader);
		runDoraemonBundle1.getBundleBean(DemoFacade.class).doSomething();
	}
}
```
想咨询一下有哪些可能会导致类似的错误信息？

**Comment by qianxingchuan** [comment]
这个错，是因为要在你的应用工程里面引用facade对应的包，你看一下我的样例工程里面的pom的引用，那个facade不属于任意一个bundle的私有的，是bundle全局共享的

**Comment by qianxingchuan** [comment]
如果还有疑问，方便把工程打包上传，下班后我研究一下

**Comment by qianxingchuan** [comment]
目测是因为DemoFacade.class要么在bundle里面没有生成bean，要么是因为没有在app所在的工程，没有引入facade

**Comment by qianxingchuan** [comment]
可能 doraemon-spring-boot-starter 这个starter是你需要的

**Comment by qianxingchuan** [comment]
我写了一个样例，doraemon-spring-boot-example,你看一下，
doraemon.config.bundlePath设置bundle的路径

**Comment by galaxyyao** [comment]
> 我写了一个样例，doraemon-spring-boot-example,你看一下，
> doraemon.config.bundlePath设置bundle的路径
非常感谢回复！

**Comment by galaxyyao** [comment]
非常感谢解答！

我梳理了一下原始项目里对于doraemon-facade和sample-auth-facade的依赖（略过archetype的）：
- sample-auth-bundle1
	- doraemon-facade【框架】
	- sample-auth-facade【当前sample项目】
- sample-auth-bundle2
	- doraemon-facade【框架】
	- sample-auth-facade【当前sample项目】
- sample-auth-project
	- sample-auth-facade【当前sample项目】
	
我先做了个不依赖doraemon-sprign-boot-starter的范例。
把sample project提取了出来，代码仓库位置：https://github.com/galaxyyao/classloader-isolation-doraemon-demo
demo项目里内部的依赖关系分别是：
- parent pom
	- 依赖无
- doraemon-demo2-facade
	- 依赖无
- doraemon-demo2-bundle1
	- doraemon-facade【框架】
	- doraemon-demo2-facade【当前项目】
	- spring-context
- doraemon-demo2-app
	- asgard-doraemon【框架】
	- doraemon-demo2-facade【当前项目】
	- springboot的一系列依赖
应该和源代码中的依赖关系是一致的。

在运行app项目之前，先进行mvn clean install package，然后将doraemon-demo2-bundle1的target里的zip包复制到doraemon-demo2-app模块的resources里。
接下来，运行doraemon-demo2-app，会遇到以下错误。
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.example.doraemon.demo2.facade.Demo2Facade' available

我全局搜索了一下，的确只有在facade的target里有Demo2Facade.class

我之后再试下添加了doraemon-spring-boot-starter后的情况。

**Comment by galaxyyao** [comment]
初步定位到原因了。参考的是这篇文章：https://www.cnblogs.com/wolbo/p/11510351.html
估计原因是项目使用dev-tools启动，所以classLoader是RestartClassLoader，但Demo2Facade是在AppClassLoader里，所以就出现了NoSuchBeanDefinitionException的错误
